### ISSUE TITLE
Simplify registration of pairs with traits

### ISSUE THREAD

**Issue by friedger** [psq/swapr#2]
It was mentioned that the contract can now be simplified.

What exactly?

**Comment by psq** [comment]
that's the version in the `trait` branch I was referring to (https://github.com/psq/swapr/blob/trait/contracts/swapr.clar), which no longer requires a registry, and 1 single contract can support multiple pairs.  I'm still using a list to keep track of the available pairs so the UI can get a list, but once there are services that index this data (it doesn't necessarily belongs in the stacks node itself), that can be removed.  The list keeps the number of pairs limited because it will max out, unlike the map.
